name: Build using .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Check for tabs
      run: |
        find "(" -name "*.cs" -or -name "*.lua" -or -name "*.jl" -or -name "*.lang" -or -name "*.xml" -or -name "*.yaml" -or -name "*.yml" -or -name "*.txt" -or -name "*.md" ")" -exec grep -Pl "\t" {} \; > matches.txt
        grep "" matches.txt && exit 1 || echo "No tab found!"

    - name: Check for CRLF
      run: |
        find "(" -name "*.cs" -or -name "*.lua" -or -name "*.jl" -or -name "*.lang" -or -name "*.xml" -or -name "*.yaml" -or -name "*.yml" -or -name "*.txt" -or -name "*.md" ")" -exec grep -Plz "\r\n" {} \; > matches.txt
        grep "" matches.txt && exit 1 || echo "No CRLF found!"

    - name: Check for trailing spaces
      run: |
        find "(" -name "*.cs" -or -name "*.lua" -or -name "*.jl" -or -name "*.lang" -or -name "*.xml" -or -name "*.yaml" -or -name "*.yml" -or -name "*.txt" -or -name "*.md" ")" -exec grep -Pl " $" {} \; > matches.txt
        grep "" matches.txt && exit 1 || echo "No trailing space found!"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5

    - name: Restore with .NET Core
      run: dotnet restore

    - name: Build using .NET Core
      run: dotnet build ExtendedVariantMode.sln --configuration Release --no-restore

    - name: Publish release
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/gh-actions'
      env:
        ZIPNAME: ExtendedVariantMode
        GITHUB_SHA: ${{ github.sha }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        ZIPNAME=$ZIPNAME-${GITHUB_SHA:0:8}.zip
        zip -qq -r $ZIPNAME everest.yaml bin/Release/net452/ExtendedVariantMode.* Ahorn Dialog Graphics Loenn
        curl --fail -H 'Content-Type: multipart/form-data' -X POST -F "file=@$ZIPNAME" "$DISCORD_WEBHOOK" | jq -r '.attachments[0].url' > zip.url

    - name: TAS Check
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/gh-actions'
      env:
        GITHUB_SHA: ${{ github.sha }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        COMMIT_REF="[\`ExtendedVariantMode@${GITHUB_SHA:0:8}\`](<https://github.com/maddie480/ExtendedVariantMode/commit/${GITHUB_SHA}>)"
        docker run --rm max480/everest:tas-check ExtendedVariantMode "`cat zip.url`" \
            && curl -H 'Content-Type: application/json' -d "{\"content\": \":white_check_mark: TAS Check for ${COMMIT_REF} successful.\"}" "$DISCORD_WEBHOOK" \
            || (curl -H 'Content-Type: application/json' -d "{\"content\": \":x: TAS Check for ${COMMIT_REF} failed!\"}" "$DISCORD_WEBHOOK" && exit 1)